theme: jekyll-theme-minimal

title: Leetware
description: Technology Research and Development

logo: assets/Logo.png
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]

about-p1: Leetware is a technology consulting company which tackles cutting edge technical challenges.
about-p2: Capitalising on New Zealand's (beautiful) culture of creative thinking and getting things done, 
  Leetware is fast building a reputation for next-level development with a core focus on design quality and productivity.


software-languages: embedded C, C++, Python, Javascript, Golang, and Rust.
electronic-disciplines: power electronics, embedded systems, sensors, and avionics.
modelling-disciplines: orbital mechanics, aerodynamics, thermal, electronic, and mechanical systems.

linkedin: https://www.linkedin.com/in/hoanibryson
email: hoani.bryson@leetware.co.nz