theme: jekyll-theme-minimal

title: Leet NZ
description: Technology Research and Development

logo: assets/logo.png
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]

software-languages: Embedded C, C++, Python, Javascript, Rust and others.
electronic-disciplines: Power Electronics, Embedded Systems, Sensors, and Avionics.
modelling-disciplines: Orbital Mechanics, Aerodynamics, Thermal, Electronic and Mechanical Systems.

linkedin: https://www.linkedin.com/in/hoanibryson
email: hoani.bryson@gmail.com